#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 19 16:08:21 2023

@author: jennywhiteley

Code modified by Gabe Decker from Jenny's code which originally plotted one day's total power values.
"""

# Code to take the txt files generated by running the ' Power_w_time.py' code that 
#are stored in the day folder and graphs the total power for every 
#half-hour of avaliable data. Code outputs a png graph for each day 
# listed in the months 'day.txt' file and locates these graphs in 
#the monthyear folder.

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as colors
from os.path import exists


def getTimeInDoY(powr):
    """
    Takes powr 2-D numpy array (of floats).
    Each subarray has the following relevant indexes:
        0 - year
        1 - month
        2 - day of the month
        3 - hour of the day
    Returns an array of equal length that just has the [day of year].[hour / 24 hr]
    """
    outlist = []
    for i in range(len(powr)):
        year = powr[i][0]
        month = powr[i][1]
        dayOfMonth = powr[i][2]
        hourOfDay = powr[i][3]

        dayFraction = hourOfDay / 24
        dayOfYearAdd = 0
        isLeapYear = year % 4 == 0

        if month == 1:
            dayOfYearAdd = 0
        elif month == 2:
            dayOfYearAdd = 31
        elif month == 3:
            if isLeapYear:
                dayOfYearAdd = 60
            else:
                dayOfYearAdd = 59
        elif month == 4:
            if isLeapYear:
                dayOfYearAdd = 91
            else:
                dayOfYearAdd = 90
        elif month == 5:
            if isLeapYear:
                dayOfYearAdd = 121
            else:
                dayOfYearAdd = 120
        elif month == 6:
            if isLeapYear:
                dayOfYearAdd = 152
            else:
                dayOfYearAdd = 151
        elif month == 7:
            if isLeapYear:
                dayOfYearAdd = 182
            else:
                dayOfYearAdd = 181
        elif month == 8:
            if isLeapYear:
                dayOfYearAdd = 213
            else:
                dayOfYearAdd = 212
        elif month == 9:
            if isLeapYear:
                dayOfYearAdd = 244
            else:
                dayOfYearAdd = 243
        elif month == 10:
            if isLeapYear:
                dayOfYearAdd = 274
            else:
                dayOfYearAdd = 273
        elif month == 11:
            if isLeapYear:
                dayOfYearAdd = 305
            else:
                dayOfYearAdd = 304
        elif month == 12:
            if isLeapYear:
                dayOfYearAdd = 335
            else:
                dayOfYearAdd = 334
        else:
            print("WARNING!! The month may not be correct")

        outlist.append(dayOfYearAdd + dayOfMonth + dayFraction)

    return np.array(outlist)


def getXLimits(mon, year):
    """
    Returns appropriate x-axis limits for each month in a leap year or non-leap year.
    I try to include one day on each end that isn't in the month so that the plot looks better.
    """
    isLeapYear = int(year) % 4 == 0
    if mon == "Jan":
        return 0, 32
    elif mon == "Feb":
        if isLeapYear:
            return 31, 61
        else:
            return 31, 60
    elif mon == "Mar":
        if isLeapYear:
            return 60, 92
        else:
            return 59, 91
    elif mon == "Apr":
        if isLeapYear:
            return 91, 122
        else:
            return 90, 121
    elif mon == "May":
        if isLeapYear:
            return 121, 153
        else:
            return 120, 152
    elif mon == "Jun":
        if isLeapYear:
            return 152, 183
        else:
            return 151, 182
    elif mon == "Jul":
        if isLeapYear:
            return 182, 214
        else:
            return 181, 213
    elif mon == "Aug":
        if isLeapYear:
            return 213, 245
        else:
            return 212, 244
    elif mon == "Sep":
        if isLeapYear:
            return 244, 275
        else:
            return 243, 274
    elif mon == "Oct":
        if isLeapYear:
            return 274, 306
        else:
            return 273, 305
    elif mon == "Nov":
        if isLeapYear:
            return 305, 336
        else:
            return 304, 335
    elif mon == "Dec":
        if isLeapYear:
            return 335, 367
        else:
            return 334, 366
    else:
        print("WARNING!! The month may not be correct")




# NOTE: You should run this in the AMTM_McMurdo directory
mainpath = '.' 

months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']  # Full month names
mons = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']  #Abbreviated version is needed as its used in day folders
#years = ['2016']
years = ['2017']


for i in range(np.size(years)): # code going into each year folder
    year = years[i]

    if not exists(year):
        continue

    color = "blue"

    print(year)
    for i in range(np.size(months)): # once inside the year, going into each month folder
        month = months[i]
        mon = mons[i]

        if not exists(f'{year}/{month}{year}'):
            continue

        print(month)
        path = mainpath +f'/{year}/{month}{year}/' 

        daypath = path + 'days.txt'  # path to get to the days.txt file
        with open(daypath, 'r') as dayfile:   # opens the days.txt file to get days with data                .
                                              #within each month, also the names of the next 
                                              # layer of folders

            days =[]
            for line in dayfile:
                if line[0] != '#':
                    if line.rstrip() != mon: # takes away the \n, 
                        justday = []
                        a =  mon+line.rstrip()    #a and b are used because I ran out of meaningful names
                        b = a.replace(" ","_",1) #this replace is necessary as the txt file has whitespace
                        entry = b.replace(" ","-",1) #where the folders have _ and -'s
                        days.append(entry)

            for i in range(len(days)):
                date, sep, nix = days[i].partition('_')

                date2 = date + '_'
                justday.append(date2)


                    #the days.txt  is closed, so we're using the 'days' list to get 
                    #to the power and time logs for each day

        f = plt.figure(figsize=(9,8))
        for n in range(0,len(days)): 

            day = days[n]
            filethere = mainpath+f'/{year}/{month}{year}/{day}/'\

            file0 = filethere +  'TempOH0_TOTAL.csv' 
            file1 = filethere + 'TempOH1_TOTAL.csv'
            onlyday = justday[n]
            dayfolder = path+f'{day}'
            power = dayfolder + '/T_and_power.txt'

            if exists(file0) == True and exists(file1) == True:
                powr = np.loadtxt(power) #opens the files in a np, index-able array 6 column array,
                # 0-year 1-month 2-day 3-time in decimal hour
                # 4- power value(x) 5-exponent(y) of power in base 10(power)
                lp = len(powr)

                plt.plot(getTimeInDoY(powr), (powr[0:lp,4]), marker = '.',linestyle = 'solid', markersize = 5, color = f'{color}' )
            else:
                print(f"WARNING: {day} is too short to have TempOH1_TOTAL.csv file, so its total power won't be used.")

        plt.title(f'Total Power {month}, {year}')
        plt.ylabel('Total power')
        plt.ylim([0*10**(-5),3.5*10**(-5)]) #All plots will have same scales
        plt.xlabel('Day of Year')
        xlim0, xlim1 = getXLimits(mon, year)
        plt.xlim(xlim0,xlim1)

        saveLocation = path + f'../{mon}Totpowr{year}.png' # NOTE: putting file in year folder
        plt.savefig(saveLocation)
        plt.close()
print('Finis')
