#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 19 16:08:21 2023

@author: jennywhiteley

Code modified by Gabe Decker from Jenny's code which originally plotted one day's total power values.
"""

# Code to take the txt files generated by running the ' Power_w_time.py' code that 
#are stored in the day folder and graphs the total power for every 
#half-hour of avaliable data. Code outputs a png graph for each day 
# listed in the months 'day.txt' file and locates these graphs in 
#the monthyear folder.

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as colors
from os.path import exists


def getTimeInDoY(powr):
    """
    Takes powr 2-D numpy array (of floats).
    Each subarray has the following relevant indexes:
        0 - year
        1 - month
        2 - day of the month
        3 - hour of the day
    Returns an array of equal length that just has the [day of year].[hour / 24 hr]
    """
    outlist = []
    for i in range(len(powr)):
        year = powr[i][0]
        month = powr[i][1]
        dayOfMonth = powr[i][2]
        hourOfDay = powr[i][3]

        dayFraction = hourOfDay / 24
        dayOfYearAdd = 0
        isLeapYear = year % 4 == 0

        if month == 1:
            dayOfYearAdd = 0
        elif month == 2:
            dayOfYearAdd = 31
        elif month == 3:
            if isLeapYear:
                dayOfYearAdd = 60
            else:
                dayOfYearAdd = 59
        elif month == 4:
            if isLeapYear:
                dayOfYearAdd = 91
            else:
                dayOfYearAdd = 90
        elif month == 5:
            if isLeapYear:
                dayOfYearAdd = 121
            else:
                dayOfYearAdd = 120
        elif month == 6:
            if isLeapYear:
                dayOfYearAdd = 152
            else:
                dayOfYearAdd = 151
        elif month == 7:
            if isLeapYear:
                dayOfYearAdd = 182
            else:
                dayOfYearAdd = 181
        elif month == 8:
            if isLeapYear:
                dayOfYearAdd = 213
            else:
                dayOfYearAdd = 212
        elif month == 9:
            if isLeapYear:
                dayOfYearAdd = 244
            else:
                dayOfYearAdd = 243
        elif month == 10:
            if isLeapYear:
                dayOfYearAdd = 274
            else:
                dayOfYearAdd = 273
        elif month == 11:
            if isLeapYear:
                dayOfYearAdd = 305
            else:
                dayOfYearAdd = 304
        elif month == 12:
            if isLeapYear:
                dayOfYearAdd = 335
            else:
                dayOfYearAdd = 334
        else:
            print("WARNING!! The month may not be correct")

        outlist.append(dayOfYearAdd + dayOfMonth + dayFraction)

    return np.array(outlist)


def getPowrForYear(year, mons, months, mainpath):
    if not exists(year):
        return

    print(year)
    powrs = []
    for i in range(np.size(months)): # once inside the year, going into each month folder
        month = months[i]
        mon = mons[i]

        if not exists(f'{year}/{month}{year}'):
            continue

        print(month)
        path = mainpath +f'/{year}/{month}{year}/' 

        daypath = path + 'days.txt'  # path to get to the days.txt file
        with open(daypath, 'r') as dayfile:   # opens the days.txt file to get days with data                .
                                              #within each month, also the names of the next 
                                              # layer of folders

            days =[]
            for line in dayfile:
                if line[0] != '#':
                    if line.rstrip() != mon: # takes away the \n, 
                        justday = []
                        a =  mon+line.rstrip()    #a and b are used because I ran out of meaningful names
                        b = a.replace(" ","_",1) #this replace is necessary as the txt file has whitespace
                        entry = b.replace(" ","-",1) #where the folders have _ and -'s
                        days.append(entry)

            for i in range(len(days)):
                date, sep, nix = days[i].partition('_')

                date2 = date + '_'
                justday.append(date2)


                    #the days.txt  is closed, so we're using the 'days' list to get 
                    #to the power and time logs for each day

        for n in range(0,len(days)): 

            day = days[n]
            filethere = mainpath+f'/{year}/{month}{year}/{day}/'\

            file0 = filethere +  'TempOH0_TOTAL.csv' 
            file1 = filethere + 'TempOH1_TOTAL.csv'
            onlyday = justday[n]
            dayfolder = path+f'{day}'
            power = dayfolder + '/T_and_power.txt'

            if exists(file0) == True and exists(file1) == True:
                powrs.append(np.loadtxt(power))  #opens the files in a np, index-able array 6 column array,
            else:
                print(f"WARNING: {day} is too short to have TempOH1_TOTAL.csv file, so its total power won't be used.")
    return powrs



# NOTE: You should run this in the AMTM_McMurdo directory
mainpath = '.' 

#months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']  # Full month names
#mons = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']  #Abbreviated version is needed as its used in day folders

year1 = '2016'
months1 = ['September', 'October', 'November']
mons1 = ['Sep', 'Oct', 'Nov']
year2 = '2017'
months2 = ['January', 'February', 'March', 'April']
mons2 = ['Jan', 'Feb', 'Mar', 'Apr']

color1 = "blue"
dataLabel1 = f"{year1} Total Power"
color2 = "red"
dataLabel2 = f"{year2} Total Power"

title = f"Total Power Winter {year1}-{year2}"


f = plt.figure(figsize=(13,13))

# powr layout
# 0-year 1-month 2-day 3-time in decimal hour
# 4- power value(x) 5-exponent(y) of power in base 10(power)
year1_powrs = getPowrForYear(year1, mons1, months1, mainpath)
year2_powrs = getPowrForYear(year2, mons2, months2, mainpath)

for i in range(len(year1_powrs)):
    powr = year1_powrs[i]
    currentLabel = dataLabel1 if i == 0 else "_nolegend_"

    lp = len(powr)
    plt.plot(getTimeInDoY(powr), (powr[0:lp,4]), marker = '.',linestyle = 'solid', markersize = 5, color = f'{color1}', label=currentLabel)
for i in range(len(year2_powrs)):
    powr = year2_powrs[i]
    currentLabel = dataLabel2 if i == 0 else "_nolegend_"

    lp = len(powr)
    plt.plot(getTimeInDoY(powr), (powr[0:lp,4]), marker = '.',linestyle = 'solid', markersize = 5, color = f'{color2}', label=currentLabel)

plt.title(title, fontsize=26)
plt.ylabel('Total power', fontsize=22)
#plt.ylim([0*10**(-5),3.5*10**(-5)]) #All plots will have same scales
plt.xlabel('Day of Year', fontsize=22)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)

plt.legend(fontsize=20)

saveLocation = mainpath + f'../Totpowr_winter_{year1}_to_{year2}.png'
plt.savefig(saveLocation)
plt.close()
print('Finis')
